---
- name: deploy DB
  hosts: dbservers
  remote_user: vagrant
  roles:
    - role: common
    - role: memcached
    - role: mysql
  tags: db

- name: deploy Admin
  hosts: adminservers
  remote_user: vagrant
  roles:
    - role: common
    - role: nginx
    - role: composer
  tags: admin
